----------------------------------------------------------------------------------------------------------------
------------------ Scripts for converting ObjectTranslation to Jsonb -------------------------------------------
----------------------------------------------------------------------------------------------------------------
alter table dataelement add column translations jsonb; 
alter table categorycombo add column translations jsonb; 
alter table attribute add column translations jsonb; 
alter table categoryoptioncombo add column translations jsonb; 
alter table categoryoptiongroupset add column translations jsonb; 
alter table categoryoptiongroup add column translations jsonb; 
alter table dataelementcategoryoption add column translations jsonb; 
alter table chart add column translations jsonb; 
alter table colorset add column translations jsonb; 
alter table color add column translations jsonb; 
alter table constant add column translations jsonb; 
alter table dashboarditem add column translations jsonb; 
alter table dashboard add column translations jsonb; 
alter table dataapprovallevel add column translations jsonb; 
alter table dataapprovalworkflow add column translations jsonb; 
alter table dataelementcategory add column translations jsonb; 
alter table dataelementgroupset add column translations jsonb; 
alter table dataelementgroup add column translations jsonb; 
alter table dataentryform add column translations jsonb; 
alter table dataset add column translations jsonb; 
alter table document add column translations jsonb; 
alter table eventchart add column translations jsonb; 
alter table eventreport add column translations jsonb; 
alter table indicatorgroupset add column translations jsonb; 
alter table indicator add column translations jsonb; 
alter table indicatortype add column translations jsonb; 
alter table maplegendset add column translations jsonb; 
alter table maplegend add column translations jsonb; 
alter table map add column translations jsonb; 
alter table mapview add column translations jsonb; 
alter table optiongroupset add column translations jsonb; 
alter table optiongroup add column translations jsonb; 
alter table optionset add column translations jsonb; 
alter table optionvalue add column translations jsonb; 
alter table organisationunit add column translations jsonb; 
alter table orgunitgroupset add column translations jsonb; 
alter table orgunitgroup add column translations jsonb; 
alter table orgunitlevel add column translations jsonb; 
alter table predictorgroup add column translations jsonb; 
alter table programindicatorgroup add column translations jsonb; 
alter table programindicator add column translations jsonb; 
alter table programmessage add column translations jsonb; 
alter table programrule add column translations jsonb; 
alter table programsection add column translations jsonb; 
alter table programstagesection add column translations jsonb; 
alter table programstage add column translations jsonb; 
alter table program_attribute_group add column translations jsonb; 
alter table program add column translations jsonb; 
alter table relationshiptype add columnn translations jsonb; 
alter table reporttable add column translations jsonb; 
alter table report add column translations jsonb; 
alter table trackedentityattribute add column translations jsonb; 
alter table trackedentitytype add column translations jsonb; 
alter table usergroup add column translations jsonb; 
alter table userrole add column translations jsonb; 
alter table validationrule add column translations jsonb; 
alter table indicatorgroup add column translations jsonb; 
alter table validationrulegroup add column translations jsonb; 

update dataelement o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join dataelementtranslations t on ot.objecttranslationid = t.objecttranslationid  where t.dataelementid = o.dataelementid );
update attribute o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join attributetranslations t on ot.objecttranslationid = t.objecttranslationid  where t.attributeid = o.attributeid );
update categorycombo o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join categorycombotranslations t on ot.objecttranslationid = t.objecttranslationid  where t.categorycomboid = o.categorycomboid );
update categoryoptioncombo o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join categoryoptioncombotranslations t on ot.objecttranslationid = t.objecttranslationid  where t.categoryoptioncomboid = o.categoryoptioncomboid );
update categoryoptiongroupset o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join categoryoptiongroupsettranslations t on ot.objecttranslationid = t.objecttranslationid  where t.categoryoptiongroupsetid = o.categoryoptiongroupsetid );
update categoryoptiongroup o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join categoryoptiongrouptranslations t on ot.objecttranslationid = t.objecttranslationid  where t.categoryoptiongroupid = o.categoryoptiongroupid );
update dataelementcategoryoption o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join categoryoptiontranslations t on ot.objecttranslationid = t.objecttranslationid  where t.categoryoptionid = o.categoryoptionid );
update chart o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join charttranslations t on ot.objecttranslationid = t.objecttranslationid  where t.chartid = o.chartid );
update colorset o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join colorsettranslations t on ot.objecttranslationid = t.objecttranslationid  where t.colorsetid = o.colorsetid );
update color o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join colortranslations t on ot.objecttranslationid = t.objecttranslationid  where t.colorid = o.colorid );                   
update constant o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join constanttranslations t on ot.objecttranslationid = t.objecttranslationid  where t.colorid = o.constantid );                                                 
update dashboarditem o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join dashboarditemtranslations t on ot.objecttranslationid = t.objecttranslationid  where t.dashboarditemid = o.dashboarditemid );
update dashboard o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join dashboardtranslations t on ot.objecttranslationid = t.objecttranslationid  where t.dashboardid = o.dashboardid );
update dataapprovallevel o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join dataapprovalleveltranslations t on ot.objecttranslationid = t.objecttranslationid  where t.dataapprovallevelid = o.dataapprovallevelid );
update dataapprovalworkflow o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join dataapprovalworkflowtranslations t on ot.objecttranslationid = t.objecttranslationid  where t.workflowid = o.workflowid );                           
update dataelementcategory o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join dataelementcategorytranslations t on ot.objecttranslationid = t.objecttranslationid  where t.categoryid = o.categoryid );                           
update dataelementgroupset o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join dataelementgroupsettranslations t on ot.objecttranslationid = t.objecttranslationid  where t.dataelementgroupsetid = o.dataelementgroupsetid );                           
update dataelementgroup o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join dataelementgrouptranslations t on ot.objecttranslationid = t.objecttranslationid  where t.dataelementgroupid = o.dataelementgroupid );
update dataentryform o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join dataentryformtranslations t on ot.objecttranslationid = t.objecttranslationid  where t.dataentryformid = o.dataentryformid );
update dataset o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join datasettranslations t on ot.objecttranslationid = t.objecttranslationid  where t.datasetid = o.datasetid );              
update document o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join documenttranslations t on ot.objecttranslationid = t.objecttranslationid  where t.documentid = o.documentid );              
update eventchart o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join eventcharttranslations t on ot.objecttranslationid = t.objecttranslationid  where t.eventchartid = o.eventchartid );              
update eventreport o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join eventreporttranslations t on ot.objecttranslationid = t.objecttranslationid  where t.eventreportid = o.eventreportid );              
update indicatorgroupset o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join indicatorgroupsettranslations t on ot.objecttranslationid = t.objecttranslationid  where t.indicatorgroupsetid = o.indicatorgroupsetid );                                
update indicator o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join indicatortranslations t on ot.objecttranslationid = t.objecttranslationid  where t.indicatorid = o.indicatorid );
update indicatortype o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join indicatortypetranslations t on ot.objecttranslationid = t.objecttranslationid  where t.indicatortypeid = o.indicatortypeid );
update maplegendset o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join maplegendsettranslations t on ot.objecttranslationid = t.objecttranslationid  where t.maplegendsetid = o.maplegendsetid );
update maplegend o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join maplegendtranslations t on ot.objecttranslationid = t.objecttranslationid  where t.maplegendid = o.maplegendid );
update map o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join maptranslations t on ot.objecttranslationid = t.objecttranslationid  where t.mapid = o.mapid );
update mapview o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join mapviewtranslations t on ot.objecttranslationid = t.objecttranslationid  where t.mapviewid = o.mapviewid );
update optiongroupset o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join optiongroupsettranslations t on ot.objecttranslationid = t.objecttranslationid  where t.optiongroupsetid = o.optiongroupsetid );
update optiongroup o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join optiongrouptranslations t on ot.objecttranslationid = t.objecttranslationid  where t.optiongroupid = o.optiongroupid );                         
update optionset o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join optionsettranslations t on ot.objecttranslationid = t.objecttranslationid  where t.optionsetid = o.optionsetid );                
update optionvalue o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join optionvaluetranslations t on ot.objecttranslationid = t.objecttranslationid  where t.optionvalueid = o.optionvalueid );                               
update organisationunit o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join organisationunittranslations t on ot.objecttranslationid = t.objecttranslationid  where t.organisationunitid = o.organisationunitid );                                                  
update orgunitgroupset o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join orgunitgroupsettranslations t on ot.objecttranslationid = t.objecttranslationid  where t.orgunitgroupsetid = o.orgunitgroupsetid );                                                  
update orgunitgroup o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join orgunitgrouptranslations t on ot.objecttranslationid = t.objecttranslationid  where t.orgunitgroupid = o.orgunitgroupid );
update orgunitlevel o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join orgunitleveltranslations t on ot.objecttranslationid = t.objecttranslationid  where t.orgunitlevelid = o.orgunitlevelid );                                       
update predictorgroup o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join predictorgrouptranslations t on ot.objecttranslationid = t.objecttranslationid  where t.predictorgroupid = o.predictorgroupid );
update programindicatorgroup o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join programindicatorgrouptranslations t on ot.objecttranslationid = t.objecttranslationid  where t.programindicatorgroupid = o.programindicatorgroupid );
update programindicator o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join programindicatortranslations t on ot.objecttranslationid = t.objecttranslationid  where t.programindicatorid = o.programindicatorid );
update programmessage o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join programmessagetranslations t on ot.objecttranslationid = t.objecttranslationid  where t.id = o.id );           
update programrule o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join programruletranslations t on ot.objecttranslationid = t.objecttranslationid  where t.programruleid = o.programruleid );                 
update programsection o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join programsectiontranslations t on ot.objecttranslationid = t.objecttranslationid  where t.programsectionid = o.programsectionid );
update programstagesection o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join programstagesectiontranslations t on ot.objecttranslationid = t.objecttranslationid  where t.programstagesectionid = o.programstagesectionid );
update programstage o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join programstagetranslations t on ot.objecttranslationid = t.objecttranslationid  where t.programstageid = o.programstageid );
update program_attribute_group o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join programtrackedentityattributegrouptranslations t on ot.objecttranslationid = t.objecttranslationid  where t.programtrackedentityattributegroupid = o.programtrackedentityattributegroupid );        
update program o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join programtranslations t on ot.objecttranslationid = t.objecttranslationid  where t.programid = o.programid );
update relationshiptype o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join relationshiptypetranslations t on ot.objecttranslationid = t.objecttranslationid  where t.relationshiptypeid = o.relationshiptypeid );
update reporttable o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join reporttabletranslations t on ot.objecttranslationid = t.objecttranslationid  where t.reporttableid = o.reporttableid );
update report o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join reporttranslations t on ot.objecttranslationid = t.objecttranslationid  where t.reportid = o.reportid );
update trackedentityattribute o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join trackedentityattributetranslations t on ot.objecttranslationid = t.objecttranslationid  where t.trackedentityattributeid = o.trackedentityattributeid );
update trackedentitytype o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join trackedentitytranslations t on ot.objecttranslationid = t.objecttranslationid  where t.trackedentitytypeid = o.trackedentitytypeid );
update usergroup o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join usergrouptranslations t on ot.objecttranslationid = t.objecttranslationid  where t.usergroupid = o.usergroupid );
update userrole o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join userroletranslations t on ot.objecttranslationid = t.objecttranslationid  where t.userroleid = o.userroleid );
update validationrule o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join validationruletranslations t on ot.objecttranslationid = t.objecttranslationid  where t.validationruleid = o.validationruleid );
update indicatorgroup o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join indicatorgrouptranslations t on ot.objecttranslationid = t.objecttranslationid  where t.indicatorgroupid = o.indicatorgroupid );
update validationrulegroup o set translations = (select to_jsonb(array_agg(jsonb_build_object('locale',locale,'property', property,'value', value ))) from objecttranslation ot inner join validationrulegrouptranslations t on ot.objecttranslationid = t.objecttranslationid  where t.validationrulegroupid = o.validationrulegroupid );
        
drop table attributetranslations;
drop table categorycombotranslations;
drop table categoryoptioncombotranslations;
drop table categoryoptiongroupsettranslations;
drop table categoryoptiongrouptranslations;
drop table categoryoptiontranslations;
drop table charttranslations;
drop table colorsettranslations;
drop table colortranslations;
drop table constanttranslations;
drop table dashboarditemtranslations;
drop table dashboardtranslations;
drop table dataapprovalleveltranslations;
drop table dataapprovalworkflowtranslations;
drop table dataelementcategorytranslations;
drop table dataelementgroupsettranslations;
drop table dataelementgrouptranslations;
drop table dataelementoperandtranslations;
drop table dataelementtranslations;
drop table dataentryformtranslations;
drop table datasetsectiontranslations;
drop table datasettranslations;
drop table documenttranslations;
drop table eventcharttranslations;
drop table eventreporttranslations;
drop table indicatorgroupsettranslations;
drop table indicatorgrouptranslations;
drop table indicatortranslations;
drop table indicatortypetranslations;
drop table interpretationcommenttranslations;
drop table interpretationtranslations;
drop table maplayertranslations;
drop table maplegendsettranslations;
drop table maplegendtranslations;
drop table maptranslations;
drop table mapviewtranslations;
drop table messageconversationtranslations;
drop table messagetranslations;
drop table metadatafiltertranslations;
drop table optiongroupsettranslations;
drop table optiongrouptranslations;
drop table optionsettranslations;
drop table optionvaluetranslations;
drop table organisationunittranslations;
drop table orgunitgroupsettranslations;
drop table orgunitgrouptranslations;
drop table orgunitleveltranslations;
drop table periodtranslations;
drop table predictorgrouptranslations;
drop table programattributestranslations;
drop table programindicatorgrouptranslations;
drop table programindicatortranslations;
drop table programinstancetranslations;
drop table programmessagetranslations;
drop table programruleactiontranslations;
drop table programruletranslations;
drop table programrulevariabletranslations;
drop table programsectiontranslations;
drop table programstagedataelementtranslations;
drop table programstageinstancetranslations;
drop table programstagesectiontranslations;
drop table programstagetranslations;
drop table programtrackedentityattributegrouptranslations;
drop table programtranslations;
drop table programvalidationtranslations;
drop table relationshiptypetranslations;
drop table reporttabletranslations;
drop table reporttranslations;
drop table statisticstranslations;
drop table trackedentityattributegrouptranslations;
drop table trackedentityattributetranslations;
drop table trackedentityinstanceremindertranslations;
drop table trackedentityinstancetranslations;
drop table trackedentitytranslations;
drop table usergrouptranslations;
drop table userinfotranslations;
drop table userroletranslations;
drop table usertranslations;
drop table validationcriteriatranslations;
drop table validationrulegrouptranslations;
drop table validationruletranslations;
----------------------------------------------------------------------------------------------------------------
------------------ End Scripts for converting ObjectTranslation to Jsonb ---------------------------------------
----------------------------------------------------------------------------------------------------------------