
function getLocaleFromURL() {
    const queryParams = new URLSearchParams(window.location.search);
    const locale = queryParams.get('locale');
    return locale || 'en';
    
}

// Localization object
const localizationMap = {
    en: {
        latestVersion: "Latest version",
        hotfix: "Hotfix",
        latestPatch: "Latest patch",
        released: "Released",
        releaseNotes: "release notes",
        upgradeNotes: "upgrade notes",
        featureOverview: "Feature overview",
        download: "Download",
        downloadOnGitHub: "Download on GitHub",
        downloadOnGooglePlay: "Download on Google Play",
        androidCompatibility: "Android compatibility:",
        minimum: "minimum",
        recommended: "recommended",
        dhis2Compatibility: "DHIS2 compatibility:",
        downloadFromDocker: "Download from",
        dockerImages: "Docker images",
        with: "with",
        sha256sum: "SHA256SUM",
        showSuperseded: "Show superseded patches",
        introduced: "Introduced:",
        tablePatch: "Patch",
        tableReleaseDate: "Release date",
        tableProductionFile: "Production WAR file",
        tableSize: "Size",
        tableNotes: "Notes",
        sampleDatabase: "Sample database",
        supported: "Supported",
        noLongerMaintained: "No longer maintained",
        targetReleaseDate: "Target release date",
        jiraLink01: "See the list of fixes so far for",
        jiraLink02: "this patch on Jira"
    },
    fr: {
        latestVersion: "Dernière version",
        hotfix: "Correctif",
        latestPatch: "Dernier patch",
        released: "Publié",
        releaseNotes: "notes de version",
        upgradeNotes: "notes de mise à niveau",
        featureOverview: "Aperçu des fonctionnalités",
        download: "Télécharger",
        downloadOnGitHub: "Télécharger sur GitHub",
        downloadOnGooglePlay: "Télécharger sur Google Play",
        androidCompatibility: "Compatibilité Android :",
        minimum: "minimum",
        recommended: "recommandé",
        dhis2Compatibility: "Compatibilité DHIS2 :",
        downloadFromDocker: "Télécharger depuis",
        dockerImages: "images Docker",
        with: "avec",
        sha256sum: "SHA256SUM",
        showSuperseded: "Afficher les correctifs remplacés",
        introduced: "Introduit :",
        tablePatch: "Patch",
        tableReleaseDate: "Date de publication",
        tableProductionFile: "Fichier WAR de production",
        tableSize: "Taille",
        tableNotes: "Notes",
        sampleDatabase: "Base de données d'exemple",
        supported: "Pris en charge",
        noLongerMaintained: "N'est plus maintenu",
        targetReleaseDate: "Date de sortie prévue",
        jiraLink01: "Voir la liste des correctifs jusqu'à présent pour",
        jiraLink02: "ce patch sur Jira"
    },
    es: {
        latestVersion: "Última versión",
        hotfix: "Corrección urgente",
        latestPatch: "Último parche",
        released: "Lanzado",
        releaseNotes: "notas de la versión",
        upgradeNotes: "notas de actualización",
        featureOverview: "Descripción de características",
        download: "Descargar",
        downloadOnGitHub: "Descargar en GitHub",
        downloadOnGooglePlay: "Descargar en Google Play",
        androidCompatibility: "Compatibilidad con Android:",
        minimum: "mínimo",
        recommended: "recomendado",
        dhis2Compatibility: "Compatibilidad con DHIS2:",
        downloadFromDocker: "Descargar desde",
        dockerImages: "imágenes de Docker",
        with: "con",
        sha256sum: "SHA256SUM",
        showSuperseded: "Mostrar parches reemplazados",
        introduced: "Introducido:",
        tablePatch: "Parche",
        tableReleaseDate: "Fecha de lanzamiento",
        tableProductionFile: "Archivo WAR de producción",
        tableSize: "Tamaño",
        tableNotes: "Notas",
        sampleDatabase: "Base de datos de muestra",
        supported: "Soportado",
        noLongerMaintained: "Ya no se mantiene",
        targetReleaseDate: "Fecha de lanzamiento prevista",
        jiraLink01: "Ver la lista de correcciones hasta ahora para",
        jiraLink02: "este parche en Jira"
    },
    pt: {
        latestVersion: "Versão mais recente",
        hotfix: "Correção urgente",
        latestPatch: "Última correção",
        released: "Lançado",
        releaseNotes: "notas de lançamento",
        upgradeNotes: "notas de atualização",
        featureOverview: "Visão geral de recursos",
        download: "Baixar",
        downloadOnGitHub: "Baixar no GitHub",
        downloadOnGooglePlay: "Baixar no Google Play",
        androidCompatibility: "Compatibilidade com Android:",
        minimum: "mínimo",
        recommended: "recomendado",
        dhis2Compatibility: "Compatibilidade com DHIS2:",
        downloadFromDocker: "Baixar de",
        dockerImages: "imagens Docker",
        with: "com",
        sha256sum: "SHA256SUM",
        showSuperseded: "Mostrar correções substituídas",
        introduced: "Introduzido:",
        tablePatch: "Correção",
        tableReleaseDate: "Data de lançamento",
        tableProductionFile: "Arquivo WAR de produção",
        tableSize: "Tamanho",
        tableNotes: "Notas",
        sampleDatabase: "Banco de dados de exemplo",
        supported: "Suportado",
        noLongerMaintained: "Não é mais mantido",
        targetReleaseDate: "Data de lançamento prevista",
        jiraLink01: "Veja a lista de correções até agora para",
        jiraLink02: "esta correção no Jira"
    }
}; 