name: App Releases Fetcher

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '52 23 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install markdown

    - name: Run the script
      run: python3 tools/app-release-notes/generate_app_notes.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}
        
    - name: pull any other changes
      run: git pull
      shell: bash  
      
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        directory: website/data/
        branch: master
        github_token: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}

   
