name: Roadmap Sync

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '12 0 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jira
        pip install pandas

    - name: Run the script
      run: python3 tools/roadmap/jira_product_discovery.py
      shell: bash
      env:
        JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_PROJECT_KEY: ROADMAP
        
    - name: pull any other changes
      run: git pull
      shell: bash  
      
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        directory: roadmap/
        branch: master
        github_token: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}

   
